-- RankData/PRIEST.lua -- GENERATED, do not hand-edit.
-- Source: this client's own Talent.dbc/Spell.dbc/SpellDuration.dbc
-- (see CLAUDE.md, "Rank data source" section -- NOT the octowow.st scrape).
-- Regenerate with: python3 tools/gen_rank_data.py
-- Generated: 2026-08-31
--
-- Keyed [tree][tier][column] (tree = the `tab` GetTalentInfo takes, 1-3,
-- ordered via TalentTab.dbc's OrderIndex field -- NOT raw tab id order,
-- which gets 7 of 9 classes wrong).
--   n = name (validated against live GetTalentInfo before use)
--   r = max rank
--   d = { [rank] = ... }, 1-indexed. Each entry is EITHER a plain
--       rendered string, OR (when the real value depends on the
--       player's live character level -- e.g. Serrated Blades'
--       armor-ignore, Ice Barrier's absorb -- see CLAUDE.md's
--       2026-08-31 level-scaling follow-up) a table
--       { t = template, s = { {b=,p=,bl=,ml=,sl=,op=,n=}, ... } }
--       where `t` contains one \2 byte per entry in `s`;
--       TalentStage_RenderRankText computes each slot live via
--       TalentStage_ComputeLevelScaled(UnitLevel("player"), ...).
--       The whole `d` entry is OMITTED (nil) whenever any rank's
--       text used a token this generator doesn't confidently
--       resolve at all -- TalentStage falls back to its normal
--       live-scrape tooltip for that talent.

TalentStage_RankData = TalentStage_RankData or {}
TalentStage_RankData["PRIEST"] = {
	[1] = {
		[1] = {
			[1] = { n = "Wand Specialization", r = 2, d = { { t = "Increases your damage and chance to hit with Wands and Bows by 13% and 5%, respectively.  Successful Wand and Bow attacks have a chance to restore  mana.", s = { { b = 0, p = 1 } } }, { t = "Increases your damage and chance to hit with Wands and Bows by 25% and 10%, respectively.  Successful Wand and Bow attacks have a chance to restore  mana.\nHigher chance to trigger than Wand Specialization (Rank 1).", s = { { b = 0, p = 1 } } } } },
			[2] = { n = "Piercing Light", r = 3, d = { "Reduces the chance for enemies to resist your Holy and Discipline spells by 2%.", "Reduces the chance for enemies to resist your Holy and Discipline spells by 4%.", "Reduces the chance for enemies to resist your Holy and Discipline spells by 6%." } },
			[3] = { n = "Mental Agility", r = 5, d = { "Reduces the mana cost of your instant cast spells and offensive Holy and Discipline spells by 2%.", "Reduces the mana cost of your instant cast spells and offensive Holy and Discipline spells by 4%.", "Reduces the mana cost of your instant cast spells and offensive Holy and Discipline spells by 6%.", "Reduces the mana cost of your instant cast spells and offensive Holy and Discipline spells by 8%.", "Reduces the mana cost of your instant cast spells and offensive Holy and Discipline spells by 10%." } },
		},
		[2] = {
			[1] = { n = "Silent Resolve", r = 5, d = { "Reduces the threat generated by your spells by 4%.", "Reduces the threat generated by your spells by 8%.", "Reduces the threat generated by your spells by 12%.", "Reduces the threat generated by your spells by 16%.", "Reduces the threat generated by your spells by 20%." } },
			[2] = { n = "Unbreakable Will", r = 5, d = { "Increases your chance to resist Stun, Fear, and Silence effects by an additional 3%.", "Increases your chance to resist Stun, Fear, and Silence effects by an additional 6%.", "Increases your chance to resist Stun, Fear, and Silence effects by an additional 9%.", "Increases your chance to resist Stun, Fear, and Silence effects by an additional 12%.", "Increases your chance to resist Stun, Fear, and Silence effects by an additional 15%." } },
			[3] = { n = "Blessed Concentration", r = 2, d = { "Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 10%.", "Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 20%." } },
			[4] = { n = "Improved Power Word: Fortitude", r = 2, d = { "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%.", "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%." } },
		},
		[3] = {
			[1] = { n = "Improved Inner Fire", r = 2, d = { "Increases the effects of your Inner Fire spell by 15%.", "Increases the effects of your Inner Fire spell by 30%." } },
			[2] = { n = "Inner Focus", r = 1, d = { "When activated, reduces the Mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect." } },
			[3] = { n = "Improved Power Word: Shield", r = 3, d = { "Increases the damage absorbed by your Power Word: Shield by 5%.", "Increases the damage absorbed by your Power Word: Shield by 10%.", "Increases the damage absorbed by your Power Word: Shield by 15%." } },
			[4] = { n = "Meditation", r = 3, d = { "Allows 5% of your Mana regeneration to continue while casting.", "Allows 10% of your Mana regeneration to continue while casting.", "Allows 15% of your Mana regeneration to continue while casting." } },
		},
		[4] = {
			[1] = { n = "Searing Light", r = 3, d = { "Your damaging Holy and Discipline spell critical strikes have a 33% chance to cause your next Smite spell to be instant cast and cost 60% less mana.  Lasts 10 sec.", "Your damaging Holy and Discipline spell critical strikes have a 66% chance to cause your next Smite spell to be instant cast and cost 60% less mana.  Lasts 10 sec.", "Your damaging Holy and Discipline spell critical strikes have a 100% chance to cause your next Smite spell to be instant cast and cost 60% less mana.  Lasts 10 sec." } },
			[2] = { n = "Purifying Flames", r = 2, d = { "Your Holy Fire has a 50% chance to increase your Holy damage by 12% for 10 sec.", "Your Holy Fire has a 100% chance to increase your Holy damage by 12% for 10 sec." } },
		},
		[5] = {
			[1] = { n = "Mental Strength", r = 3, d = { "Increases your total Intellect by 3% and your spell casting speed by 1%.", "Increases your total Intellect by 6% and your spell casting speed by 2%.", "Increases your total Intellect by 10% and your spell casting speed by 3%." } },
			[2] = { n = "Enlighten", r = 1, d = { "Bring a party member under your tutelage for 30 min. Whenever you cast a Discipline or Holy spell, you have a 10% chance with helpful spells, or 15% chance with harmful spells, to burn them for 4% of their total health as Holy damage and increase both your and their spell damage and healing by 10% for 8 sec.  If cast on yourself, the spell damage and healing bonus is increased to 15%.  Only one party member can be under your tutelage at a time." } },
			[3] = { n = "Resurgent Shield", r = 1, d = { "When your Power Word: Shield is broken, 25% of its base mana cost is refunded and increases damage and healing done by Holy spells and effects by up to 10% of the shield's total absorption amount for 8 sec." } },
		},
		[6] = {
			[3] = { n = "Force of Will", r = 5, d = { "Increases your spell damage and the critical strike chance of your offensive spells by 1% and the amount of damage absorbed by your Power Word: Shield by 4%.", "Increases your spell damage and the critical strike chance of your offensive spells by 2% and the amount of damage absorbed by your Power Word: Shield by 8%.", "Increases your spell damage and the critical strike chance of your offensive spells by 3% and the amount of damage absorbed by your Power Word: Shield by 12%.", "Increases your spell damage and the critical strike chance of your offensive spells by 4% and the amount of damage absorbed by your Power Word: Shield by 16%.", "Increases your spell damage and the critical strike chance of your offensive spells by 5% and the amount of damage absorbed by your Power Word: Shield by 20%." } },
		},
		[7] = {
			[2] = { n = "Chastise", r = 1, d = { "Chastise the target, causing 160 Holy damage.  If the target is an enemy, they are disoriented for up to 2 sec or until they take damage.  If the target is an ally, their attack and casting speed is increased by 13% for 8 sec, increased to 12 sec if the damage results in a critical strike.  Cannot be used on allies with less than 80% health or below level 35." } },
		},
	},
	[2] = {
		[1] = {
			[1] = { n = "Improved Renew", r = 3, d = { "Increases the amount healed by your Renew spell by 5%.", "Increases the amount healed by your Renew spell by 10%.", "Increases the amount healed by your Renew spell by 15%." } },
			[2] = { n = "Holy Focus", r = 2, d = { "Gives you a 35% chance to avoid interruption caused by damage while casting any Holy spell.", "Gives you a 70% chance to avoid interruption caused by damage while casting any Holy spell." } },
			[3] = { n = "Divinity", r = 5, d = { "Increases the critical effect chance of your Holy and Discipline spells by 1%.", "Increases the critical effect chance of your Holy and Discipline spells by 2%.", "Increases the critical effect chance of your Holy and Discipline spells by 3%.", "Increases the critical effect chance of your Holy and Discipline spells by 4%.", "Increases the critical effect chance of your Holy and Discipline spells by 5%." } },
		},
		[2] = {
			[2] = { n = "Divine Fury", r = 5, d = { "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1 sec.", "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2 sec.", "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3 sec.", "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4 sec.", "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5 sec." } },
			[3] = { n = "Spell Warding", r = 3, d = { "Reduces all spell damage taken by 3%.", "Reduces all spell damage taken by 6%.", "Reduces all spell damage taken by 10%." } },
			[4] = { n = "Holy Reach", r = 2, d = { "Increases the range of your Smite, Holy Fire and Chastise spells and the radius of your Prayer of Healing and Holy Nova spells by 10%.", "Increases the range of your Smite, Holy Fire and Chastise spells and the radius of your Prayer of Healing and Holy Nova spells by 20%." } },
		},
		[3] = {
			[2] = { n = "Blessed Recovery", r = 3, d = { "After being struck by a melee or ranged critical hit, heal 8% of the damage taken over 6 sec.", "After being struck by a melee or ranged critical hit, heal 16% of the damage taken over 6 sec.", "After being struck by a melee or ranged critical hit, heal 25% of the damage taken over 6 sec." } },
			[3] = { n = "Inspiration", r = 3, d = { "Increases your target's armor by 8% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.", "Increases your target's armor by 16% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.", "Increases your target's armor by 25% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell." } },
			[4] = { n = "Holy Nova", r = 1, d = { { t = "Causes an explosion of holy light around the caster, causing  Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for . Using this spell while in Shadowform damages you instead of healing you. These effects cause reduced threat.", s = { { b = 30, p = 0.2, bl = 20, ml = 26, sl = 20 }, { b = 60, p = 0.4, bl = 20, ml = 26, sl = 20 } } } } },
		},
		[4] = {
			[1] = { n = "Empowered Recovery", r = 2, d = { "Increases the duration of Renew by 3 sec and increases healing done by your healing spells by 3% to targets affected by Renew.", "Increases the duration of Renew by 3 sec and increases healing done by your healing spells by 6% to targets affected by Renew." } },
			[2] = { n = "Improved Healing", r = 3, d = { "Reduces the Mana cost of your Lesser Heal, Heal, Greater Heal and Prayer of Healing spells by 5%.", "Reduces the Mana cost of your Lesser Heal, Heal, Greater Heal and Prayer of Healing spells by 10%.", "Reduces the Mana cost of your Lesser Heal, Heal, Greater Heal and Prayer of Healing spells by 15%." } },
			[3] = { n = "Spiritual Guidance", r = 5, d = { "Increases spell damage and healing by up to 5% of your total Spirit.", "Increases spell damage and healing by up to 10% of your total Spirit.", "Increases spell damage and healing by up to 15% of your total Spirit.", "Increases spell damage and healing by up to 20% of your total Spirit.", "Increases spell damage and healing by up to 25% of your total Spirit." } },
		},
		[5] = {
			[1] = { n = "Book of Prayer", r = 2, d = { "Whenever you cast a healing spell, you regain 15% of its mana cost if it is different from your previous healing spell.", "Whenever you cast a healing spell, you regain 30% of its mana cost if it is different from your previous healing spell." } },
			[2] = { n = "Spirit of Redemption", r = 1, d = { "Increases total Spirit by 10%. Upon death, the priest becomes the Spirit of Redemption for 10 sec. While in this form, the priest cannot move, attack, be attacked, or be targeted by spells or effects, but can cast healing spells at no cost. When the effect ends, the priest dies." } },
			[3] = { n = "Reservoir of Light", r = 3, d = { "Increases the effectiveness of Lightwell's Splendor of Light by 33%.", "Increases the effectiveness of Lightwell's Splendor of Light by 66%.", "Increases the effectiveness of Lightwell's Splendor of Light by 100%." } },
		},
		[6] = {
			[3] = { n = "Spiritual Healing", r = 5, d = { "Increases the amount healed by your healing spells by 6%.", "Increases the amount healed by your healing spells by 12%.", "Increases the amount healed by your healing spells by 18%.", "Increases the amount healed by your healing spells by 24%.", "Increases the amount healed by your healing spells by 30%." } },
		},
		[7] = {
			[2] = { n = "Ascendance", r = 1, d = { "Calls upon divine aid, purging all forms of crowd control and empowering your healing spells. Healing spells cost 33% less mana and their cast time is reduced by 20%. Allies healed gain Apotheosis, increasing healing received by 15% for 10 sec. Lasts 30 sec." } },
		},
	},
	[3] = {
		[1] = {
			[2] = { n = "Spirit Tap", r = 5, d = { "Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or critically striking a target with Mind Blast. For the duration, mana regenerates at 50% of the normal rate while casting. Lasts 15 sec.", "Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or critically striking a target with Mind Blast. For the duration, mana regenerates at 50% of the normal rate while casting. Lasts 15 sec.", "Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or critically striking a target with Mind Blast. For the duration, mana regenerates at 50% of the normal rate while casting. Lasts 15 sec.", "Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or critically striking a target with Mind Blast. For the duration, mana regenerates at 50% of the normal rate while casting. Lasts 15 sec.", "Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or critically striking a target with Mind Blast. For the duration, mana regenerates at 50% of the normal rate while casting. Lasts 15 sec." } },
			[3] = { n = "Improved Mind Blast", r = 5, d = { "Reduces the cooldown of your Mind Blast spell by 0.5 sec.", "Reduces the cooldown of your Mind Blast spell by 1 sec.", "Reduces the cooldown of your Mind Blast spell by 1.5 sec.", "Reduces the cooldown of your Mind Blast spell by 2 sec.", "Reduces the cooldown of your Mind Blast spell by 2.5 sec." } },
		},
		[2] = {
			[1] = { n = "Shadow Affinity", r = 3, d = { "Reduces the threat generated by your Shadow spells by 8%.", "Reduces the threat generated by your Shadow spells by 16%.", "Reduces the threat generated by your Shadow spells by 25%." } },
			[2] = { n = "Improved Shadow Word: Pain", r = 2, d = { "Increases the duration of your Shadow Word: Pain spell by 3 sec.", "Increases the duration of your Shadow Word: Pain spell by 6 sec." } },
			[3] = { n = "Shadow Focus", r = 5, d = { "Reduces your target's chance to resist your Shadow spells by 2%.", "Reduces your target's chance to resist your Shadow spells by 4%.", "Reduces your target's chance to resist your Shadow spells by 6%.", "Reduces your target's chance to resist your Shadow spells by 8%.", "Reduces your target's chance to resist your Shadow spells by 10%." } },
			[4] = { n = "Blackout", r = 5, d = { "Gives your Shadow damage spells a 2% chance to stun the target for 2 sec.", "Gives your Shadow damage spells a 4% chance to stun the target for 2 sec.", "Gives your Shadow damage spells a 6% chance to stun the target for 2 sec.", "Gives your Shadow damage spells a 8% chance to stun the target for 2 sec.", "Gives your Shadow damage spells a 10% chance to stun the target for 2 sec." } },
		},
		[3] = {
			[1] = { n = "Improved Psychic Scream", r = 2, d = { "Reduces the cooldown of your Psychic Scream spell by 2 sec.", "Reduces the cooldown of your Psychic Scream spell by 4 sec." } },
			[2] = { n = "Improved Fade", r = 2, d = { "Reduces the cooldown of Fade by 3 sec and the threat returned when Fade ends by 25%.", "Reduces the cooldown of Fade by 6 sec and the threat returned when Fade ends by 50%." } },
			[3] = { n = "Mind Flay", r = 1, d = { "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%." } },
		},
		[4] = {
			[2] = { n = "Improved Mana Burn", r = 2, d = { "Reduces the casting time of your Mana Burn spell by 0.25 secs.", "Reduces the casting time of your Mana Burn spell by 0.5 sec." } },
			[3] = { n = "Shadow Reach", r = 2, d = { "Increases the range of your Shadow damage spells by 10%.", "Increases the range of your Shadow damage spells by 20%." } },
			[4] = { n = "Shadow Weaving", r = 5, d = { "Your Shadow damage spells have a 20% chance to grant you Shadow Weaving for 10 sec. Your Shadow damage spells apply a vulnerability that increases Shadow damage taken by 3% per stack of Shadow Weaving for 15 sec. Stacks up to 5 times.", "Your Shadow damage spells have a 40% chance to grant you Shadow Weaving for 10 sec. Your Shadow damage spells apply a vulnerability that increases Shadow damage taken by 3% per stack of Shadow Weaving for 15 sec. Stacks up to 5 times.", "Your Shadow damage spells have a 60% chance to grant you Shadow Weaving for 10 sec. Your Shadow damage spells apply a vulnerability that increases Shadow damage taken by 3% per stack of Shadow Weaving for 15 sec. Stacks up to 5 times.", "Your Shadow damage spells have a 80% chance to grant you Shadow Weaving for 10 sec. Your Shadow damage spells apply a vulnerability that increases Shadow damage taken by 3% per stack of Shadow Weaving for 15 sec. Stacks up to 5 times.", "Your Shadow damage spells have a 100% chance to grant you Shadow Weaving for 10 sec. Your Shadow damage spells apply a vulnerability that increases Shadow damage taken by 3% per stack of Shadow Weaving for 15 sec. Stacks up to 5 times." } },
		},
		[5] = {
			[1] = { n = "Silence", r = 1, d = { "Silences the target, preventing them from casting spells for 5 sec." } },
			[2] = { n = "Vampiric Embrace", r = 1, d = { "Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow spell damage you deal for 1 min." } },
			[3] = { n = "Vampiric Touch", r = 2, d = { "Increases the percentage healed by Vampiric Embrace by an additional 2% and your Vampiric Embrace now causes all party members to also gain mana equal to 1% of any Shadow spell damage you deal.", "Increases the percentage healed by Vampiric Embrace by an additional 5% and your Vampiric Embrace now causes all party members to also gain mana equal to 2% of any Shadow spell damage you deal." } },
		},
		[6] = {
			[3] = { n = "Darkness", r = 5, d = { "Increases your Shadow spell damage by 2%.", "Increases your Shadow spell damage by 4%.", "Increases your Shadow spell damage by 6%.", "Increases your Shadow spell damage by 8%.", "Increases your Shadow spell damage by 10%." } },
		},
		[7] = {
			[2] = { n = "Shadowform", r = 1, d = { "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%.  However, you may not cast Holy spells with the exception of Holy Nova while in this form." } },
		},
	},
}
