-- RankData/WARRIOR.lua -- GENERATED, do not hand-edit.
-- Source: this client's own Talent.dbc/Spell.dbc/SpellDuration.dbc
-- (see CLAUDE.md, "Rank data source" section -- NOT the octowow.st scrape).
-- Regenerate with: python3 tools/gen_rank_data.py
-- Generated: 2026-08-31
--
-- Keyed [tree][tier][column] (tree = the `tab` GetTalentInfo takes, 1-3,
-- ordered via TalentTab.dbc's OrderIndex field -- NOT raw tab id order,
-- which gets 7 of 9 classes wrong).
--   n = name (validated against live GetTalentInfo before use)
--   r = max rank
--   d = { [rank] = ... }, 1-indexed. Each entry is EITHER a plain
--       rendered string, OR (when the real value depends on the
--       player's live character level -- e.g. Serrated Blades'
--       armor-ignore, Ice Barrier's absorb -- see CLAUDE.md's
--       2026-08-31 level-scaling follow-up) a table
--       { t = template, s = { {b=,p=,bl=,ml=,sl=,op=,n=}, ... } }
--       where `t` contains one \2 byte per entry in `s`;
--       TalentStage_RenderRankText computes each slot live via
--       TalentStage_ComputeLevelScaled(UnitLevel("player"), ...).
--       The whole `d` entry is OMITTED (nil) whenever any rank's
--       text used a token this generator doesn't confidently
--       resolve at all -- TalentStage falls back to its normal
--       live-scrape tooltip for that talent.

TalentStage_RankData = TalentStage_RankData or {}
TalentStage_RankData["WARRIOR"] = {
	[1] = {
		[1] = {
			[1] = { n = "Improved Heroic Strike", r = 3, d = { "Reduces the cost of your Heroic Strike ability by 1 rage point.", "Reduces the cost of your Heroic Strike ability by 2 rage points.", "Reduces the cost of your Heroic Strike ability by 3 rage points." } },
			[2] = { n = "Tactical Mastery", r = 5, d = { "You retain up to 5 of your rage points when you change stances.", "You retain up to 10 of your rage points when you change stances.", "You retain up to 15 of your rage points when you change stances.", "You retain up to 20 of your rage points when you change stances.", "You retain up to 25 of your rage points when you change stances." } },
			[3] = { n = "Improved Rend", r = 2, d = { "Increases the bleed damage done by your Rend ability by 10%.", "Increases the bleed damage done by your Rend ability by 20%." } },
		},
		[2] = {
			[1] = { n = "Improved Charge", r = 2, d = { "Increases the amount of rage generated by your Charge ability by 5.", "Increases the amount of rage generated by your Charge ability by 10." } },
			[2] = { n = "Deflection", r = 5, d = { "Increases your Parry chance by 1%.", "Increases your Parry chance by 2%.", "Increases your Parry chance by 3%.", "Increases your Parry chance by 4%.", "Increases your Parry chance by 5%." } },
			[4] = { n = "Improved Thunder Clap", r = 3, d = { "Reduces the cost of your Thunder Clap ability by 1 rage point and increases the damage by 20%.", "Reduces the cost of your Thunder Clap ability by 2 rage point and increases the damage by 40%.", "Reduces the cost of your Thunder Clap ability by 4 rage point and increases the damage by 60%." } },
		},
		[3] = {
			[1] = { n = "Master Strike", r = 1, d = { "Performs a skillful attack, dealing 35% weapon damage and causing an additional effect depending on your main hand weapon.\n\nMace: Disorients the target for 3 sec. Any damage caused will remove the effect.\nSword: Disarms the target for 3 sec.\nAxe: Immobilizes the target for 4 sec.\nPolearm: Deals an additional 100% weapon damage if the target is mounted and dismounts them.\nFist Weapon: Knocks down the target for 2 sec.\nStaff: Increases your chance to parry by 25% for 10 sec.\nDagger: Silences the target for 3 sec." } },
			[2] = { n = "Improved Overpower", r = 2, d = { "Increases the critical strike chance of your Overpower ability by 25%.", "Increases the critical strike chance of your Overpower ability by 50%." } },
			[3] = { n = "Deep Wounds", r = 3, d = { "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 6 sec.", "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 6 sec.", "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 6 sec." } },
		},
		[4] = {
			[2] = { n = "Two-Handed Weapon Specialization", r = 3, d = { "Increases the damage you deal with two-handed melee weapons by 2% and increases your skill in all two-handed weapons by 1.", "Increases the damage you deal with two-handed melee weapons by 4% and increases your skill in all two-handed weapons by 2.", "Increases the damage you deal with two-handed melee weapons by 6% and increases your skill in all two-handed weapons by 3." } },
			[3] = { n = "Impale", r = 2, d = { "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.", "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%." } },
		},
		[5] = {
			[1] = { n = "Master of Arms", r = 5, d = { "Adds the following effects to your weapons, based on the weapon type:\n\nAxe - Increases your chance to get a critical strike by 1%.\nMace - Causes your attacks to ignore 1.2 of your target's Armor per level.\nSword - Gives you a 1% chance to get an extra attack on the same target after hitting your target.\nPolearm - Increases the range of melee attacks by 0.4 yd.", "Adds the following effects to your weapons, based on the weapon type:\n\nAxe - Increases your chance to get a critical strike by 2%.\nMace - Causes your attacks to ignore 2.4 of your target's Armor per level.\nSword - Gives you a 2% chance to get an extra attack on the same target after hitting your target.\nPolearm - Increases the range of melee attacks by 0.8 yd.", "Adds the following effects to your weapons, based on the weapon type:\n\nAxe - Increases your chance to get a critical strike by 3%.\nMace - Causes your attacks to ignore 3.6 of your target's Armor per level.\nSword - Gives you a 3% chance to get an extra attack on the same target after hitting your target.\nPolearm - Increases the range of melee attacks by 1.2 yd.", "Adds the following effects to your weapons, based on the weapon type:\n\nAxe - Increases your chance to get a critical strike by 4%.\nMace - Causes your attacks to ignore 4.8 of your target's Armor per level.\nSword - Gives you a 4% chance to get an extra attack on the same target after hitting your target.\nPolearm - Increases the range of melee attacks by 1.6 yd.", "Adds the following effects to your weapons, based on the weapon type:\n\nAxe - Increases your chance to get a critical strike by 5%.\nMace - Causes your attacks to ignore 6 of your target's Armor per level.\nSword - Gives you a 5% chance to get an extra attack on the same target after hitting your target.\nPolearm - Increases the range of melee attacks by 2.0 yd." } },
			[2] = { n = "Sweeping Strikes", r = 1, d = { "Your next 5 abilities and main-hand melee attacks strike an additional nearby opponent." } },
			[3] = { n = "Boundless Anger", r = 3, d = { "Increases your maximum Rage by 10.1.", "Increases your maximum Rage by 20.1.", "Increases your maximum Rage by 30.1." } },
			[4] = { n = "Improved Disciplines", r = 3, d = { "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min.", "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 8 min.", "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 12 min." } },
		},
		[6] = {
			[1] = { n = "Improved Slam", r = 2, d = { "Reduces the cast time and global cooldown of your Slam ability by 0.25 sec.", "Reduces the cast time and global cooldown of your Slam ability by 0.5 sec." } },
			[3] = { n = "Precision Cut", r = 3, d = { "Increases damage dealt per extra rage point spent on Execute by 25%.", "Increases damage dealt per extra rage point spent on Execute by 50%.", "Increases damage dealt per extra rage point spent on Execute by 75%." } },
		},
		[7] = {
			[2] = { n = "Mortal Strike", r = 1, d = { "A vicious strike that deals 115% weapon damage and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec." } },
		},
	},
	[2] = {
		[1] = {
			[2] = { n = "Booming Voice", r = 5, d = { "Increases the area of effect of all shouts by 12% and the duration of your Battle and Demoralizing Shout by 12%.", "Increases the area of effect of all shouts by 24% and the duration of your Battle and Demoralizing Shout by 24%.", "Increases the area of effect of all shouts by 36% and the duration of your Battle and Demoralizing Shout by 36%.", "Increases the area of effect of all shouts by 48% and the duration of your Battle and Demoralizing Shout by 48%.", "Increases the area of effect of all shouts by 60% and the duration of your Battle and Demoralizing Shout by 60%." } },
			[3] = { n = "Cruelty", r = 5, d = { "Increases your chance to get a critical strike with melee weapons by 1%.", "Increases your chance to get a critical strike with melee weapons by 2%.", "Increases your chance to get a critical strike with melee weapons by 3%.", "Increases your chance to get a critical strike with melee weapons by 4%.", "Increases your chance to get a critical strike with melee weapons by 5%." } },
		},
		[2] = {
			[2] = { n = "Dual Wield Specialization", r = 5, d = { "Increases the damage done by your offhand weapon by 5% and your chance to hit with your offhand weapon by 2%.", "Increases the damage done by your offhand weapon by 10% and your chance to hit with your offhand weapon by 4%.", "Increases the damage done by your offhand weapon by 15% and your chance to hit with your offhand weapon by 6%.", "Increases the damage done by your offhand weapon by 20% and your chance to hit with your offhand weapon by 8%.", "Increases the damage done by your offhand weapon by 25% and your chance to hit with your offhand weapon by 10%." } },
			[3] = { n = "Unbridled Wrath", r = 5, d = { "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.", "Gives you a 30% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.", "Gives you a 45% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.", "Gives you a 60% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.", "Gives you a 75% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons." } },
		},
		[3] = {
			[1] = { n = "Improved Shouts", r = 5, d = { "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%.", "Increases the melee attack power bonus of your Battle Shout by 10% and increases the melee attack power reduction of your Demoralizing Shout by 16%.", "Increases the melee attack power bonus of your Battle Shout by 15% and increases the melee attack power reduction of your Demoralizing Shout by 24%.", "Increases the melee attack power bonus of your Battle Shout by 20% and increases the melee attack power reduction of your Demoralizing Shout by 32%.", "Increases the melee attack power bonus of your Battle Shout by 25% and increases the melee attack power reduction of your Demoralizing Shout by 40%." } },
			[2] = { n = "Piercing Howl", r = 1, d = { "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec." } },
			[3] = { n = "Blood Craze", r = 3, d = { "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.", "Regenerates 4% of your total Health over 6 sec after being the victim of a critical strike.", "Regenerates 6% of your total Health over 6 sec after being the victim of a critical strike." } },
		},
		[4] = {
			[2] = { n = "Battlefield Mobility", r = 2, d = { "Reduces the cooldown of your Intercept and Intervene abilities by 5 sec, and your Charge ability by 2 sec.", "Reduces the cooldown of your Intercept and Intervene abilities by 10 sec, and your Charge ability by 4 sec." } },
			[3] = { n = "Enrage", r = 5, d = { "Gives you a 4% melee damage bonus for 8 sec after being the victim of a critical strike.", "Gives you a 8% melee damage bonus for 8 sec after being the victim of a critical strike.", "Gives you a 12% melee damage bonus for 8 sec after being the victim of a critical strike.", "Gives you a 16% melee damage bonus for 8 sec after being the victim of a critical strike.", "Gives you a 20% melee damage bonus for 8 sec after being the victim of a critical strike." } },
			[4] = { n = "Improved Pummel", r = 2, d = { "Gives your Pummel ability a 50% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 1 sec.", "Gives your Pummel ability a 100% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 2 sec." } },
		},
		[5] = {
			[1] = { n = "Ravager", r = 3, d = { "Reduces the cooldown of your Whirlwind by 1 sec and the Rage cost of your Cleave by 1.", "Reduces the cooldown of your Whirlwind by 1.5 sec and the Rage cost of your Cleave by 2.", "Reduces the cooldown of your Whirlwind by 2 sec and the Rage cost of your Cleave by 3." } },
			[2] = { n = "Death Wish", r = 1, d = { "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec." } },
			[4] = { n = "Improved Execute", r = 2, d = { "Reduces the Rage cost of your Execute ability by 2.", "Reduces the Rage cost of your Execute ability by 5." } },
		},
		[6] = {
			[1] = { n = "Improved Berserker Rage", r = 2, d = { "Using Berserker Rage generates 5 Rage and grants a 50% chance to break free from movement impairing effects when activated.", "Using Berserker Rage generates 10 Rage and grants a 100% chance to break free from movement impairing effects when activated." } },
			[2] = { n = "Flurry", r = 5, d = { "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.", "Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.", "Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.", "Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.", "Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike." } },
			[3] = { n = "Blood Drinker", r = 3, d = { "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1% of your maximum health.", "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1.5% of your maximum health.", "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 2% of your maximum health." } },
		},
		[7] = {
			[2] = { n = "Bloodthirst", r = 1, d = { "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power and increasing your movement speed by 10% for 6 sec." } },
		},
	},
	[3] = {
		[1] = {
			[1] = { n = "Improved Bloodrage", r = 2, d = { "Increases the instant Rage generated by your Bloodrage ability by 5.", "Increases the instant Rage generated by your Bloodrage ability by 10." } },
			[2] = { n = "Shield Specialization", r = 5, d = { "Increases your chance to block attacks with a shield by 1% and generates 1 rage when a block occurs.", "Increases your chance to block attacks with a shield by 2% and generates 2 rage when a block occurs.", "Increases your chance to block attacks with a shield by 3% and generates 3 rage when a block occurs.", "Increases your chance to block attacks with a shield by 4% and generates 4 rage when a block occurs.", "Increases your chance to block attacks with a shield by 5% and generates 5 rage when a block occurs." } },
			[3] = { n = "Anticipation", r = 3, d = { "Increases your Defense skill by 7.", "Increases your Defense skill by 14.", "Increases your Defense skill by 20." } },
		},
		[2] = {
			[2] = { n = "Iron Will", r = 5, d = { "Increases your chance to resist Stun and Charm effects by an additional 3%.", "Increases your chance to resist Stun and Charm effects by an additional 6%.", "Increases your chance to resist Stun and Charm effects by an additional 9%.", "Increases your chance to resist Stun and Charm effects by an additional 12%.", "Increases your chance to resist Stun and Charm effects by an additional 15%." } },
			[3] = { n = "Toughness", r = 5, d = { "Increases your armor value from items by 2% and the amount of damage absorbed by your shield by 3%.", "Increases your armor value from items by 4% and the amount of damage absorbed by your shield by 6%.", "Increases your armor value from items by 6% and the amount of damage absorbed by your shield by 9%.", "Increases your armor value from items by 8% and the amount of damage absorbed by your shield by 12%.", "Increases your armor value from items by 10% and the amount of damage absorbed by your shield by 15%." } },
		},
		[3] = {
			[1] = { n = "Last Stand", r = 1, d = { "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost." } },
			[2] = { n = "Improved Intervene", r = 2, d = { "Grants a 50% chance to gain immunity to movement impairing effects for 3 sec after using Intervene.", "Grants a 100% chance to gain immunity to movement impairing effects for 3 sec after using Intervene." } },
			[3] = { n = "Improved Taunt", r = 2, d = { "Reduces the cooldown of your Taunt ability by 1 sec.", "Reduces the cooldown of your Taunt ability by 2 sec." } },
			[4] = { n = "Improved Revenge", r = 3, d = { "Gives your Revenge ability a 15% chance to stun the target for 3 sec and reduces its cooldown by 0.5 sec.", "Gives your Revenge ability a 30% chance to stun the target for 3 sec and reduces its cooldown by 1 sec.", "Gives your Revenge ability a 45% chance to stun the target for 3 sec and reduces its cooldown by 1.5 sec." } },
		},
		[4] = {
			[1] = { n = "Gag Order", r = 2, d = { "Your Shield Slam has an additional 50% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 50% chance to silence the target for 3 sec.", "Your Shield Slam has an additional 100% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 100% chance to silence the target for 3 sec." } },
			[2] = { n = "Improved Disarm", r = 2, d = { "Decreases the cooldown of your Disarm ability by 10 secs.", "Decreases the cooldown of your Disarm ability by 20 secs." } },
			[3] = { n = "Defiance", r = 5, d = { "Increases the threat generated while in Defensive Stance by an additional 4%.", "Increases the threat generated while in Defensive Stance by an additional 8%.", "Increases the threat generated while in Defensive Stance by an additional 12%.", "Increases the threat generated while in Defensive Stance by an additional 15%.", "Increases the threat generated while in Defensive Stance by an additional 20%." } },
		},
		[5] = {
			[1] = { n = "One-Handed Weapon Specialization", r = 5, d = { "Increases the damage you deal with One-Handed Melee weapons by 2%.", "Increases the damage you deal with One-Handed Melee weapons by 4%.", "Increases the damage you deal with One-Handed Melee weapons by 6%.", "Increases the damage you deal with One-Handed Melee weapons by 8%.", "Increases the damage you deal with One-Handed Melee weapons by 10%." } },
			[2] = { n = "Shield Slam", r = 1, d = { "Slam the target with your shield, causing 184 damage, modified by your shield block value and attack power. This attack causes a high amount of threat, and has a 50% chance of dispelling 1 magic effect on the target." } },
			[3] = { n = "Improved Shield Slam", r = 2, d = { "Reduces the cooldown of Shield Slam by 0.75 sec, and using this ability will also grant you an extra 35% chance to block the next attack within 4.5 sec.", "Reduces the cooldown of Shield Slam by 1.5 sec, and using this ability will also grant you an extra 70% chance to block the next attack within 4.5 sec." } },
			[4] = { n = "Reprisal", r = 2, d = { "Increases the damage dealt by your Revenge ability by 25%, and has a 50% chance to refund its rage cost if successful.", "Increases the damage dealt by your Revenge ability by 50%, and has a 100% chance to refund its rage cost if successful." } },
		},
		[6] = {
			[1] = { n = "Improved Shield Wall", r = 2, d = { "Increases the effect duration of your Shield Wall ability by 1 secs and reduces its cooldown by 5 min.", "Increases the effect duration of your Shield Wall ability by 2 secs and reduces its cooldown by 10 min." } },
			[3] = { n = "Defensive Tactics", r = 3, d = { "While wearing a shield, you retain 60% of the increased threat generation from Defensive Stance in other stances.", "While wearing a shield, you retain 120% of the increased threat generation from Defensive Stance in other stances.", "While wearing a shield, you retain 180% of the increased threat generation from Defensive Stance in other stances." } },
		},
		[7] = {
			[2] = { n = "Concussion Blow", r = 1, d = { "Deals 115 damage and stuns the opponent for 3 sec. This ability deals a high amount of threat and penetrates 100% of the enemy's armor. Instantly generates 10 rage." } },
		},
	},
}
